# Generated by Django 4.1 on 2022-10-23 09:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilitiesAndBenefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Facilities And Benefits',
                'verbose_name_plural': 'Facilities And Benefits',
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('is_unknown', models.BooleanField(default=False, verbose_name='is unknown')),
                ('organizational_category', models.CharField(choices=[('normal_worker', 'normal_worker'), ('employee', 'employee'), ('expert', 'expert'), ('senior_expert', 'senior_expert'), ('manager', 'manager'), ('assistance', 'assistance'), ('senior_manager', 'senior_manager')], max_length=75, verbose_name='organizational category')),
                ('type_of_cooperation', models.CharField(choices=[('full-time', 'full-time'), ('per time', 'per time'), ('contractual', 'contractual')], max_length=75, verbose_name='type of cooperation')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('living_same_city_preference', models.BooleanField(default=False, verbose_name='living same city preference')),
                ('remote', models.BooleanField(default=False, verbose_name='remote')),
                ('work_time', models.CharField(max_length=250, verbose_name='work time')),
                ('minimum_age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18)], verbose_name='minimum age')),
                ('maximum_age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(50)], verbose_name='maximum age')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('preferably_male', 'preferably_male'), ('preferably_female', 'preferably_female')], max_length=17, verbose_name='gender')),
                ('get_intern', models.BooleanField(default=False, verbose_name='get intern')),
                ('exemption_or_complete_military_service', models.BooleanField(default=False, verbose_name='exemption or complete military service')),
                ('amount_of_work_experience', models.PositiveIntegerField(verbose_name='amount of work experience')),
                ('languages', models.CharField(max_length=75, verbose_name='languages')),
                ('salary', models.CharField(max_length=75, verbose_name='salary')),
                ('is_show_salary', models.BooleanField(default=False, verbose_name='show salary')),
                ('job_description', models.TextField(max_length=500, verbose_name='job description')),
                ('benefits', models.ManyToManyField(to='advertisement.facilitiesandbenefits')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='accounts.companyprofile')),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
            },
        ),
    ]
