# Generated by Django 4.1 on 2022-10-18 20:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BenefitsAndFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(18)], verbose_name='minimum age')),
                ('maximum_age', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(50)], verbose_name='maximum age')),
                ('get_intern', models.BooleanField(default=False, verbose_name='get intern')),
                ('exemption_or_complete_military_service', models.BooleanField(default=False, verbose_name='exemption or complete military service')),
                ('amount_of_work_experience', models.PositiveIntegerField(verbose_name='amount of work experience')),
                ('languages', models.CharField(max_length=75, verbose_name='languages')),
            ],
            options={
                'verbose_name': 'Employment Conditions',
                'verbose_name_plural': 'Employment Conditions',
            },
        ),
        migrations.CreateModel(
            name='JobIntroduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('is_unknown', models.BooleanField(default=False, verbose_name='is unknown')),
                ('organizational_category', models.CharField(max_length=75, verbose_name='organizational category')),
                ('type_of_cooperation', models.CharField(max_length=75, verbose_name='type of cooperation')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('living_same_city_preference', models.BooleanField(default=False, verbose_name='living same city preference')),
                ('remote', models.BooleanField(default=False, verbose_name='remote')),
                ('work_time', models.CharField(max_length=250, verbose_name='work time')),
            ],
        ),
    ]
