# Generated by Django 4.1 on 2023-03-23 13:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Benefit',
                'verbose_name_plural': 'Benefits',
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='title')),
                ('organizational_category', models.CharField(max_length=40, verbose_name='organizational category')),
                ('type_of_cooperation', models.CharField(choices=[('full-time', 'تمام وقت'), ('per time', 'پاره وقت'), ('remote', 'دورکاری')], max_length=9, verbose_name='type of cooperation')),
                ('work_time', models.TimeField(blank=True, max_length=250, null=True, verbose_name='work time')),
                ('country', models.CharField(default='IR', max_length=20, verbose_name='Country')),
                ('province', models.CharField(max_length=30, verbose_name='Province')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('is_company_have_living_place', models.BooleanField(default=False, verbose_name='Is company have living place?')),
                ('minimum_age', models.PositiveIntegerField(blank=True, default=18, validators=[django.core.validators.MinValueValidator(18)], verbose_name='Minimum age')),
                ('maximum_age', models.PositiveIntegerField(blank=True, default=50, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Maximum age')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن'), ('preferably_male', 'ترجیحا مرد'), ('preferably_female', 'ترجیحا زن')], max_length=17, verbose_name='gender')),
                ('military_service_status', models.CharField(choices=[('دارای کارت پایان خدمت', 'دارای کارت پایان خدمت'), ('در حال خدمت', 'در حال خدمت'), ('معافیت پزشکی', 'معافیت پزشکی'), ('سایر معافیت ها( معافیت غیر پزشکی )', 'سایر معافیت ها( معافیت غیر پزشکی )'), ('اهمیتی ندارد', 'اهمیتی ندارد')], max_length=34, verbose_name='Military Service Status')),
                ('work_experience', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2)], verbose_name='amount of work experience')),
                ('language_level', models.CharField(blank=True, choices=[('ضعیف', 'ضعیف'), ('متوسط', 'متوسط'), ('خوب', 'خوب'), ('عالی', 'عالی')], max_length=5, verbose_name='language level')),
                ('salary', models.CharField(db_index=True, max_length=75, verbose_name='Salary')),
                ('job_description', models.TextField(blank=True, max_length=500, verbose_name='Job Description')),
                ('benefits', models.ManyToManyField(blank=True, to='advertisement.benefit', verbose_name='Benefits')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='accounts.companyprofile')),
                ('language', models.ManyToManyField(blank=True, to='accounts.language', verbose_name='Languages')),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
            },
        ),
    ]
