# Generated by Django 4.1 on 2023-01-08 08:07

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='benefits',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[], max_length=200, verbose_name='Benefits'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='is_company_have_living_place',
            field=models.BooleanField(default=False, verbose_name='Is company have living place?'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='job_description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Job Description'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='language',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Persian', 'Persian'), ('English', 'English')], max_length=100, verbose_name='Languages'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(db_index=True, max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='work_time',
            field=models.TimeField(blank=True, max_length=250, verbose_name='work time'),
        ),
    ]
