# Generated by Django 4.1 on 2022-10-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='benefits',
            field=models.ManyToManyField(blank=True, null=True, to='advertisement.facilitiesandbenefits'),
        ),
    ]
