# Generated by Django 4.1 on 2022-12-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_alter_advertisement_benefits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='city',
            field=models.CharField(choices=[('mashhad', 'mashhad')], max_length=50, verbose_name='City'),
        ),
    ]
