# Generated by Django 4.1 on 2022-10-30 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_alter_advertisement_benefits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='amount_of_work_experience',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2)], verbose_name='amount of work experience'),
        ),
    ]
