# Generated by Django 4.1 on 2023-01-08 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_alter_advertisement_benefits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='maximum_age',
            field=models.PositiveIntegerField(blank=True, default=50, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Maximum age'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='minimum_age',
            field=models.PositiveIntegerField(blank=True, default=18, validators=[django.core.validators.MinValueValidator(18)], verbose_name='Minimum age'),
        ),
    ]
