# Generated by Django 4.1 on 2022-11-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_alter_advertisement_amount_of_work_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='benefits',
            field=models.ManyToManyField(blank=True, to='advertisement.facilitiesandbenefits'),
        ),
    ]
