# Generated by Django 4.1 on 2022-10-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_advertisement_delete_benefitsandfacilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='benefits',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='benefits'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='organizational_category',
            field=models.CharField(choices=[('normal_worker', 'normal_worker'), ('employee', 'employee'), ('expert', 'expert'), ('senior_expert', 'senior_expert'), ('manager', 'manager'), ('assistance', 'assistance'), ('senior_manager', 'senior_manager')], max_length=75, verbose_name='organizational category'),
        ),
    ]
