# Generated by Django 4.1 on 2022-12-22 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_companyprofile_industry_delete_industry_and_more'),
        ('advertisement', '0004_alter_advertisement_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='accounts.companyprofile'),
        ),
    ]
