# Generated by Django 4.1 on 2022-10-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_alter_advertisement_benefits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilitiesAndBenefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Facilities And Benefits',
                'verbose_name_plural': 'Facilities And Benefits',
            },
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='benefits',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='benefits',
            field=models.ManyToManyField(to='advertisement.facilitiesandbenefits'),
        ),
    ]
