# Generated by Django 4.1 on 2022-10-20 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_facilitiesandbenefits_remove_advertisement_benefits_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='show_salary',
            new_name='is_show_salary',
        ),
    ]
