# Generated by Django 4.1 on 2022-10-21 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_alter_organizationalinterface_phone_alter_user_phone'),
        ('advertisement', '0006_rename_show_salary_advertisement_is_show_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='company',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.companyprofile'),
        ),
    ]
