# Generated by Django 4.1 on 2022-10-21 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_alter_organizationalinterface_phone_alter_user_phone'),
        ('advertisement', '0007_advertisement_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.companyprofile'),
        ),
    ]
