# Generated by Django 4.1 on 2023-01-07 19:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import extensions.utils
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(max_length=10, unique=True, validators=[extensions.utils.phone_validator], verbose_name='phone')),
                ('user_level', models.CharField(choices=[('normal', 'normal'), ('admin', 'admin'), ('super_user', 'super_user')], default='normal', max_length=10, verbose_name='user level')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active_email', models.BooleanField(default=False)),
                ('is_operator', models.BooleanField(default=False)),
                ('active_email_code', models.CharField(editable=False, max_length=32)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='BlockedPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='شماره ی تلفن نامعتبر است.', regex='^9\\d{2}\\s*?\\d{3}\\s*?\\d{4}$')], verbose_name='phone')),
            ],
            options={
                'verbose_name': 'Blocked Phone',
                'verbose_name_plural': 'Blocked Phones',
            },
        ),
        migrations.CreateModel(
            name='EducationalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_study', models.CharField(max_length=30, verbose_name='field of study')),
                ('education', models.CharField(choices=[('DIPLOMA', 'Diploma'), ('ASSOCIATE', 'Associate'), ('BACHELOR', 'Bachelor'), ('MASTER', 'Master'), ('PHD', 'Phd')], max_length=9, verbose_name='education')),
                ('university', models.CharField(max_length=100, verbose_name='University')),
                ('score', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(20)], verbose_name='score')),
            ],
            options={
                'verbose_name': 'Educational Record',
                'verbose_name_plural': 'Educational Records',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=50, verbose_name='Job')),
                ('company', models.CharField(max_length=100, verbose_name='Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=10, verbose_name='Slug Field')),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('email', models.EmailField(blank=True, max_length=254, validators=[extensions.utils.email_validator], verbose_name='Email')),
                ('avatar', models.ImageField(blank=True, upload_to='profiles/avatars/', verbose_name='Avatar')),
                ('national_code', models.CharField(max_length=10, unique=True, validators=[extensions.utils.national_code_validator], verbose_name='National code')),
                ('passport_number', models.CharField(blank=True, max_length=20, verbose_name='Passport number')),
                ('country', models.CharField(choices=[('AD', 'آندورا'), ('AE', 'امارات متحده عربی'), ('AF', 'افغانستان'), ('AG', 'آنتیگوا و باربودا'), ('AI', 'آنگویلا'), ('AL', 'آلبانی'), ('AM', 'ارمنستان'), ('AO', 'آنگولا'), ('AQ', 'جنوبگان'), ('AR', 'آرژانتین'), ('AS', 'ساموآی آمریکا'), ('AT', 'اتریش'), ('AU', 'استرالیا'), ('AW', 'آروبا'), ('AX', 'جزایر آلند'), ('AZ', 'جمهوری آذربایجان'), ('BA', 'بوسنی و هرزگوین'), ('BB', 'باربادوس'), ('BD', 'بنگلادش'), ('BE', 'بلژیک'), ('BF', 'بورکینا فاسو'), ('BG', 'بلغارستان'), ('BH', 'بحرین'), ('BI', 'بوروندی'), ('BJ', 'بنین'), ('BL', 'سنت بارثلمی'), ('BM', 'برمودا'), ('BN', 'برونئی'), ('BO', 'بولیوی'), ('BQ', 'هلند کارائیب'), ('BR', 'برزیل'), ('BS', 'باهاما'), ('BT', 'بوتان'), ('BV', 'جزیره بووه'), ('BW', 'بوتسوانا'), ('BY', 'بلاروس'), ('BZ', 'بلیز'), ('CA', 'کانادا'), ('CC', 'جزایر کوکوس'), ('CD', 'جمهوری دموکراتیک کنگو'), ('CF', 'جمهوری آفریقای مرکزی'), ('CG', 'جمهوری کنگو'), ('CH', 'سوئیس'), ('CI', 'ساحل عاج'), ('CK', 'جزایر کوک'), ('CL', 'شیلی'), ('CM', 'کامرون'), ('CN', 'چین'), ('CO', 'کلمبیا'), ('CR', 'کاستاریکا'), ('CU', 'کوبا'), ('CV', 'کیپ ورد'), ('CW', 'کوراسائو'), ('CX', 'جزیره کریسمس'), ('CY', 'قبرس'), ('CZ', 'جمهوری چک'), ('DE', 'آلمان'), ('DJ', 'جیبوتی'), ('DK', 'دانمارک'), ('DM', 'دومینیکا'), ('DO', 'دومینیکا'), ('DZ', 'الجزایر'), ('EC', 'اکوادور'), ('EE', 'استونی'), ('EG', 'مصر'), ('EH', 'صحرای غربی'), ('ER', 'اریتره'), ('ES', 'اسپانیا'), ('ET', 'اتیوپی'), ('FI', 'فنلاند'), ('FJ', 'فیجی'), ('FK', 'جزایر فالکلند'), ('FM', 'ایالات فدرال میکرونزی'), ('FO', 'جزایر فارو'), ('FR', 'فرانسه'), ('GA', 'گابن'), ('GB', 'انگلستان'), ('GD', 'گرانادا'), ('GE', 'گرجستان'), ('GF', 'گویان فرانسه'), ('GG', 'گرنزی'), ('GH', 'غنا'), ('GI', 'جبل الطارق'), ('GL', 'گرینلند'), ('GM', 'گامبیا'), ('GN', 'گینه'), ('GP', 'جزیره گوادلوپ'), ('GQ', 'گینه استوایی'), ('GR', 'یونان'), ('GS', 'جزایر جورجیای جنوبی و ساندویچ جنوبی'), ('GT', 'گواتمالا'), ('GU', 'گوام'), ('GW', 'گینه بیسائو'), ('GY', 'گویان'), ('HK', 'هنگ کنگ'), ('HM', 'جزیره هرد و جزایر مک دونالد'), ('HN', 'هندوراس'), ('HR', 'کرواسی'), ('HT', 'هائیتی'), ('HU', 'مجارستان'), ('ID', 'اندونزی'), ('IE', 'جمهوری ایرلند'), ('IL', 'فلسطین اشغالی (اسرائیل)'), ('IM', 'جزیره من'), ('IN', 'هند'), ('IO', 'قلمروی اقیانوس هند بریتانیا'), ('IQ', 'عراق'), ('IR', 'ایران'), ('IS', 'ایسلند'), ('IT', 'ایتالیا'), ('JE', 'ادبیات'), ('JM', 'جامائیکا'), ('JO', 'اردن'), ('JP', 'ژاپن'), ('KE', 'کنیا'), ('KG', 'قرقیزستان'), ('KH', 'کامبوج'), ('KI', 'کیریباتی'), ('KM', 'کومور'), ('KN', 'سنت کیتس و نویس'), ('KP', 'کره شمالی'), ('KR', 'کره جنوبی'), ('KW', 'کویت'), ('KY', 'جزایر کیمن'), ('KZ', 'قزاقستان'), ('LA', 'لائوس'), ('LB', 'لبنان'), ('LC', 'سنت لوسیا'), ('LI', 'لیختن اشتاین'), ('LK', 'سری لانکا'), ('LR', 'لیبریا'), ('LS', 'لسوتو'), ('LT', 'لیتوانی'), ('LU', 'لوکزامبورگ'), ('LV', 'لتونی'), ('LY', 'لیبی'), ('MA', 'مراکش'), ('MC', 'موناکو'), ('MD', 'مولداوی'), ('ME', 'مونته نگرو'), ('MF', 'سنت مارتین فرانسه'), ('MG', 'ماداگاسکار'), ('MH', 'جزایر مارشال'), ('MK', 'جمهوری مقدونیه'), ('ML', 'مالی'), ('MM', 'میانمار'), ('MN', 'مغولستان'), ('MO', 'ماکائو'), ('MP', 'جزایر ماریانای شمالی'), ('MQ', 'مارتینیک'), ('MR', 'موریتانی'), ('MS', 'مونتسرات'), ('MT', 'مالت'), ('MU', 'موریس'), ('MV', 'مالدیو'), ('MW', 'مالاوی'), ('MX', 'مکزیک'), ('MY', 'مالزی'), ('MZ', 'موزامبیک'), ('NA', 'نامیبیا'), ('NC', 'کالدونیای جدید'), ('NE', 'نیجر'), ('NF', 'جزیره نورفولک'), ('NG', 'نیجریه'), ('NI', 'نیکاراگوئه'), ('NL', 'هلند'), ('NO', 'نروژ'), ('NP', 'نپال'), ('NR', 'نائورو'), ('NU', 'نیوئه'), ('NZ', 'نیوزلند'), ('OM', 'عمان'), ('PA', 'پاناما'), ('PE', 'پرو'), ('PF', 'پلینزی فرانسه'), ('PG', 'پاپوآ گینه نو'), ('PH', 'فیلیپین'), ('PK', 'پاکستان'), ('PL', 'لهستان'), ('PM', 'سنت پیر و ماژلان'), ('PN', 'جزایر پیت\u200cکرن'), ('PR', 'پورتوریکو'), ('PS', 'فلسطین'), ('PT', 'پرتغال'), ('PW', 'پالائو'), ('PY', 'پاراگوئه'), ('QA', 'قطر'), ('RE', 'ریونیون'), ('RO', 'رومانی'), ('RS', 'صربستان'), ('RU', 'روسیه'), ('RW', 'رواندا'), ('SA', 'عربستان سعودی'), ('SB', 'جزایر سلیمان'), ('SC', 'سیشل'), ('SD', 'سودان'), ('SE', 'سوئد'), ('SG', 'سنگاپور'), ('SH', 'سینت هلینا'), ('SI', 'اسلوونی'), ('SJ', 'سوالبارد و یان ماین'), ('SK', 'اسلواکی'), ('SL', 'سیرالئون'), ('SM', 'سن مارینو'), ('SN', 'سنگال'), ('SO', 'سومالی'), ('SR', 'سورینام'), ('ST', 'سائوتومه و پرینسیپ'), ('SV', 'السالوادور'), ('SX', 'سنت مارتین هلند'), ('SY', 'سوریه'), ('SZ', 'سوازیلند'), ('TC', 'جزایر تورکس و کایکوس'), ('TD', 'چاد'), ('TF', 'سرزمین\u200cهای قطب جنوب و جنوبی فرانسه'), ('TG', 'توگو'), ('TH', 'تایلند'), ('TJ', 'تاجیکستان'), ('TK', 'توکلائو'), ('TL', 'تیمور شرقی'), ('TM', 'ترکمنستان'), ('TN', 'تونس'), ('TO', 'تونگا'), ('TR', 'ترکیه'), ('TT', 'ترینیداد و توباگو'), ('TV', 'تووالو'), ('TW', 'تایوان'), ('TZ', 'تانزانیا'), ('UA', 'اوکراین'), ('UG', 'اوگاندا'), ('UM', 'جزایر کوچک حاشیه\u200cای آمریکا'), ('US', 'ایالات متحده'), ('UY', 'اروگوئه'), ('UZ', 'ازبکستان'), ('VA', 'شهر واتیکان'), ('VC', 'سنت وینسنت و گرنادین'), ('VE', 'ونزوئلا'), ('VG', 'جزایر ویرجین بریتانیا'), ('VI', 'جزایر ویرجین ایالات متحده آمریکا'), ('VN', 'ویتنام'), ('VU', 'وانواتو'), ('WF', 'والیس و فوتونا'), ('WS', 'ساموآ'), ('YE', 'یمن'), ('YT', 'مایوت'), ('ZA', 'آفریقای جنوبی'), ('ZM', 'زامبیا'), ('ZW', 'زیمبابوه')], default='IR', max_length=200, verbose_name='Country')),
                ('province', models.CharField(choices=[('آذربایجان شرقی', 'آذربایجان شرقی'), ('آذربایجان غربی', 'آذربایجان غربی'), ('اردبیل', 'اردبیل'), ('اصفهان', 'اصفهان'), ('البرز', 'البرز'), ('ایلام', 'ایلام'), ('بوشهر', 'بوشهر'), ('تهران', 'تهران'), ('چهارمحال و بختیاری', 'چهارمحال و بختیاری'), ('خراسان جنوبی', 'خراسان جنوبی'), ('خراسان رضوی', 'خراسان رضوی'), ('خراسان شمالی', 'خراسان شمالی'), ('خوزستان', 'خوزستان'), ('زنجان', 'زنجان'), ('سمنان', 'سمنان'), ('سیستان و بلوچستان', 'سیستان و بلوچستان'), ('فارس', 'فارس'), ('قزوین', 'قزوین'), ('قم', 'قم'), ('کردستان', 'کردستان'), ('کرمان', 'کرمان'), ('کرمانشاه', 'کرمانشاه'), ('کهگیلویه و بویراحمد', 'کهگیلویه و بویراحمد'), ('گلستان', 'گلستان'), ('گیلان', 'گیلان'), ('لرستان', 'لرستان'), ('مازندران', 'مازندران'), ('مرکزی', 'مرکزی'), ('هرمزگان', 'هرمزگان'), ('همدان', 'همدان'), ('یزد', 'یزد')], max_length=200, verbose_name='Province')),
                ('city', models.CharField(choices=[('mashhad', 'mashhad')], max_length=200, verbose_name='City')),
                ('address', models.TextField(blank=True, max_length=500, verbose_name='Address')),
                ('is_married', models.BooleanField(default=False, verbose_name='Is Married ?')),
                ('gender', models.CharField(choices=[('female', 'خانم'), ('male', 'آقا')], max_length=6, verbose_name='Gender')),
                ('day_of_birth', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(31)], verbose_name='day of birth')),
                ('month_of_birth', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(12)], verbose_name='month of birth')),
                ('year_of_birth', models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(message='The year is Invalid.', regex='^1[34]\\d{2}$')], verbose_name='year of birth')),
                ('military_service_status', models.CharField(choices=[('دارای کارت پایان خدمت', 'دارای کارت پایان خدمت'), ('در حال خدمت', 'در حال خدمت'), ('معاف از رزم', 'معاف از رزم'), ('معافیت تحصیلی', 'معافیت تحصیلی'), ('معافیت پزشکی', 'معافیت پزشکی'), ('سایر معافیت ها', 'سایر معافیت ها')], max_length=100, verbose_name='Military Service Status')),
                ('other_exemptions', models.CharField(blank=True, max_length=100, verbose_name='other exemptions')),
                ('about_me', models.TextField(blank=True, max_length=300, verbose_name='About Me')),
                ('cv_file', models.ImageField(blank=True, upload_to='profiles/resumes/', verbose_name='CV File')),
                ('language', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Persian', 'Persian'), ('English', 'English')], max_length=7, verbose_name='language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True, verbose_name='name')),
                ('english_name', models.CharField(blank=True, max_length=120, unique=True, verbose_name='english name')),
                ('email', models.EmailField(max_length=254, validators=[extensions.utils.email_validator], verbose_name='email')),
                ('website_addr', models.CharField(blank=True, max_length=120, verbose_name='website address')),
                ('telephone', models.CharField(max_length=10, unique=True)),
                ('industry', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[], max_length=3, verbose_name='industry')),
                ('country', models.CharField(choices=[('AD', 'آندورا'), ('AE', 'امارات متحده عربی'), ('AF', 'افغانستان'), ('AG', 'آنتیگوا و باربودا'), ('AI', 'آنگویلا'), ('AL', 'آلبانی'), ('AM', 'ارمنستان'), ('AO', 'آنگولا'), ('AQ', 'جنوبگان'), ('AR', 'آرژانتین'), ('AS', 'ساموآی آمریکا'), ('AT', 'اتریش'), ('AU', 'استرالیا'), ('AW', 'آروبا'), ('AX', 'جزایر آلند'), ('AZ', 'جمهوری آذربایجان'), ('BA', 'بوسنی و هرزگوین'), ('BB', 'باربادوس'), ('BD', 'بنگلادش'), ('BE', 'بلژیک'), ('BF', 'بورکینا فاسو'), ('BG', 'بلغارستان'), ('BH', 'بحرین'), ('BI', 'بوروندی'), ('BJ', 'بنین'), ('BL', 'سنت بارثلمی'), ('BM', 'برمودا'), ('BN', 'برونئی'), ('BO', 'بولیوی'), ('BQ', 'هلند کارائیب'), ('BR', 'برزیل'), ('BS', 'باهاما'), ('BT', 'بوتان'), ('BV', 'جزیره بووه'), ('BW', 'بوتسوانا'), ('BY', 'بلاروس'), ('BZ', 'بلیز'), ('CA', 'کانادا'), ('CC', 'جزایر کوکوس'), ('CD', 'جمهوری دموکراتیک کنگو'), ('CF', 'جمهوری آفریقای مرکزی'), ('CG', 'جمهوری کنگو'), ('CH', 'سوئیس'), ('CI', 'ساحل عاج'), ('CK', 'جزایر کوک'), ('CL', 'شیلی'), ('CM', 'کامرون'), ('CN', 'چین'), ('CO', 'کلمبیا'), ('CR', 'کاستاریکا'), ('CU', 'کوبا'), ('CV', 'کیپ ورد'), ('CW', 'کوراسائو'), ('CX', 'جزیره کریسمس'), ('CY', 'قبرس'), ('CZ', 'جمهوری چک'), ('DE', 'آلمان'), ('DJ', 'جیبوتی'), ('DK', 'دانمارک'), ('DM', 'دومینیکا'), ('DO', 'دومینیکا'), ('DZ', 'الجزایر'), ('EC', 'اکوادور'), ('EE', 'استونی'), ('EG', 'مصر'), ('EH', 'صحرای غربی'), ('ER', 'اریتره'), ('ES', 'اسپانیا'), ('ET', 'اتیوپی'), ('FI', 'فنلاند'), ('FJ', 'فیجی'), ('FK', 'جزایر فالکلند'), ('FM', 'ایالات فدرال میکرونزی'), ('FO', 'جزایر فارو'), ('FR', 'فرانسه'), ('GA', 'گابن'), ('GB', 'انگلستان'), ('GD', 'گرانادا'), ('GE', 'گرجستان'), ('GF', 'گویان فرانسه'), ('GG', 'گرنزی'), ('GH', 'غنا'), ('GI', 'جبل الطارق'), ('GL', 'گرینلند'), ('GM', 'گامبیا'), ('GN', 'گینه'), ('GP', 'جزیره گوادلوپ'), ('GQ', 'گینه استوایی'), ('GR', 'یونان'), ('GS', 'جزایر جورجیای جنوبی و ساندویچ جنوبی'), ('GT', 'گواتمالا'), ('GU', 'گوام'), ('GW', 'گینه بیسائو'), ('GY', 'گویان'), ('HK', 'هنگ کنگ'), ('HM', 'جزیره هرد و جزایر مک دونالد'), ('HN', 'هندوراس'), ('HR', 'کرواسی'), ('HT', 'هائیتی'), ('HU', 'مجارستان'), ('ID', 'اندونزی'), ('IE', 'جمهوری ایرلند'), ('IL', 'فلسطین اشغالی (اسرائیل)'), ('IM', 'جزیره من'), ('IN', 'هند'), ('IO', 'قلمروی اقیانوس هند بریتانیا'), ('IQ', 'عراق'), ('IR', 'ایران'), ('IS', 'ایسلند'), ('IT', 'ایتالیا'), ('JE', 'ادبیات'), ('JM', 'جامائیکا'), ('JO', 'اردن'), ('JP', 'ژاپن'), ('KE', 'کنیا'), ('KG', 'قرقیزستان'), ('KH', 'کامبوج'), ('KI', 'کیریباتی'), ('KM', 'کومور'), ('KN', 'سنت کیتس و نویس'), ('KP', 'کره شمالی'), ('KR', 'کره جنوبی'), ('KW', 'کویت'), ('KY', 'جزایر کیمن'), ('KZ', 'قزاقستان'), ('LA', 'لائوس'), ('LB', 'لبنان'), ('LC', 'سنت لوسیا'), ('LI', 'لیختن اشتاین'), ('LK', 'سری لانکا'), ('LR', 'لیبریا'), ('LS', 'لسوتو'), ('LT', 'لیتوانی'), ('LU', 'لوکزامبورگ'), ('LV', 'لتونی'), ('LY', 'لیبی'), ('MA', 'مراکش'), ('MC', 'موناکو'), ('MD', 'مولداوی'), ('ME', 'مونته نگرو'), ('MF', 'سنت مارتین فرانسه'), ('MG', 'ماداگاسکار'), ('MH', 'جزایر مارشال'), ('MK', 'جمهوری مقدونیه'), ('ML', 'مالی'), ('MM', 'میانمار'), ('MN', 'مغولستان'), ('MO', 'ماکائو'), ('MP', 'جزایر ماریانای شمالی'), ('MQ', 'مارتینیک'), ('MR', 'موریتانی'), ('MS', 'مونتسرات'), ('MT', 'مالت'), ('MU', 'موریس'), ('MV', 'مالدیو'), ('MW', 'مالاوی'), ('MX', 'مکزیک'), ('MY', 'مالزی'), ('MZ', 'موزامبیک'), ('NA', 'نامیبیا'), ('NC', 'کالدونیای جدید'), ('NE', 'نیجر'), ('NF', 'جزیره نورفولک'), ('NG', 'نیجریه'), ('NI', 'نیکاراگوئه'), ('NL', 'هلند'), ('NO', 'نروژ'), ('NP', 'نپال'), ('NR', 'نائورو'), ('NU', 'نیوئه'), ('NZ', 'نیوزلند'), ('OM', 'عمان'), ('PA', 'پاناما'), ('PE', 'پرو'), ('PF', 'پلینزی فرانسه'), ('PG', 'پاپوآ گینه نو'), ('PH', 'فیلیپین'), ('PK', 'پاکستان'), ('PL', 'لهستان'), ('PM', 'سنت پیر و ماژلان'), ('PN', 'جزایر پیت\u200cکرن'), ('PR', 'پورتوریکو'), ('PS', 'فلسطین'), ('PT', 'پرتغال'), ('PW', 'پالائو'), ('PY', 'پاراگوئه'), ('QA', 'قطر'), ('RE', 'ریونیون'), ('RO', 'رومانی'), ('RS', 'صربستان'), ('RU', 'روسیه'), ('RW', 'رواندا'), ('SA', 'عربستان سعودی'), ('SB', 'جزایر سلیمان'), ('SC', 'سیشل'), ('SD', 'سودان'), ('SE', 'سوئد'), ('SG', 'سنگاپور'), ('SH', 'سینت هلینا'), ('SI', 'اسلوونی'), ('SJ', 'سوالبارد و یان ماین'), ('SK', 'اسلواکی'), ('SL', 'سیرالئون'), ('SM', 'سن مارینو'), ('SN', 'سنگال'), ('SO', 'سومالی'), ('SR', 'سورینام'), ('ST', 'سائوتومه و پرینسیپ'), ('SV', 'السالوادور'), ('SX', 'سنت مارتین هلند'), ('SY', 'سوریه'), ('SZ', 'سوازیلند'), ('TC', 'جزایر تورکس و کایکوس'), ('TD', 'چاد'), ('TF', 'سرزمین\u200cهای قطب جنوب و جنوبی فرانسه'), ('TG', 'توگو'), ('TH', 'تایلند'), ('TJ', 'تاجیکستان'), ('TK', 'توکلائو'), ('TL', 'تیمور شرقی'), ('TM', 'ترکمنستان'), ('TN', 'تونس'), ('TO', 'تونگا'), ('TR', 'ترکیه'), ('TT', 'ترینیداد و توباگو'), ('TV', 'تووالو'), ('TW', 'تایوان'), ('TZ', 'تانزانیا'), ('UA', 'اوکراین'), ('UG', 'اوگاندا'), ('UM', 'جزایر کوچک حاشیه\u200cای آمریکا'), ('US', 'ایالات متحده'), ('UY', 'اروگوئه'), ('UZ', 'ازبکستان'), ('VA', 'شهر واتیکان'), ('VC', 'سنت وینسنت و گرنادین'), ('VE', 'ونزوئلا'), ('VG', 'جزایر ویرجین بریتانیا'), ('VI', 'جزایر ویرجین ایالات متحده آمریکا'), ('VN', 'ویتنام'), ('VU', 'وانواتو'), ('WF', 'والیس و فوتونا'), ('WS', 'ساموآ'), ('YE', 'یمن'), ('YT', 'مایوت'), ('ZA', 'آفریقای جنوبی'), ('ZM', 'زامبیا'), ('ZW', 'زیمبابوه')], default='IR', max_length=100, verbose_name='country')),
                ('province', models.CharField(choices=[('آذربایجان شرقی', 'آذربایجان شرقی'), ('آذربایجان غربی', 'آذربایجان غربی'), ('اردبیل', 'اردبیل'), ('اصفهان', 'اصفهان'), ('البرز', 'البرز'), ('ایلام', 'ایلام'), ('بوشهر', 'بوشهر'), ('تهران', 'تهران'), ('چهارمحال و بختیاری', 'چهارمحال و بختیاری'), ('خراسان جنوبی', 'خراسان جنوبی'), ('خراسان رضوی', 'خراسان رضوی'), ('خراسان شمالی', 'خراسان شمالی'), ('خوزستان', 'خوزستان'), ('زنجان', 'زنجان'), ('سمنان', 'سمنان'), ('سیستان و بلوچستان', 'سیستان و بلوچستان'), ('فارس', 'فارس'), ('قزوین', 'قزوین'), ('قم', 'قم'), ('کردستان', 'کردستان'), ('کرمان', 'کرمان'), ('کرمانشاه', 'کرمانشاه'), ('کهگیلویه و بویراحمد', 'کهگیلویه و بویراحمد'), ('گلستان', 'گلستان'), ('گیلان', 'گیلان'), ('لرستان', 'لرستان'), ('مازندران', 'مازندران'), ('مرکزی', 'مرکزی'), ('هرمزگان', 'هرمزگان'), ('همدان', 'همدان'), ('یزد', 'یزد')], max_length=100, verbose_name='province')),
                ('city', models.CharField(choices=[('mashhad', 'mashhad')], max_length=100, verbose_name='city')),
                ('logo', models.ImageField(blank=True, upload_to='companies/logos/', verbose_name='logo')),
                ('company_description', models.TextField(blank=True, max_length=400, null=True, verbose_name='company description')),
                ('company_view', models.ImageField(blank=True, upload_to='companies/views/', verbose_name='company view')),
                ('established_year', models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(message='The year is Invalid.', regex='^1[34]\\d{2}$')], verbose_name='established year')),
                ('type_of_ownership', models.CharField(choices=[('private', 'خصوصی'), ('Governmental', 'دولتی'), ('other', 'غیره ( وقفی و ...')], max_length=12, verbose_name='type of ownership')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('number_of_ad', models.PositiveIntegerField(default=0, verbose_name='number of advertisements')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='organizational interface')),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Companies Profile',
            },
        ),
    ]
