# Generated by Django 4.1 on 2022-12-17 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='educational_record',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='language',
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, max_length=10, null=True, verbose_name='Slug Field'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='profile',
            name='educational_record',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.educationalrecord'),
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.language'),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_experience',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.workexperience'),
        ),
    ]
