# Generated by Django 4.1 on 2022-10-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='name'),
        ),
    ]
