# Generated by Django 4.1 on 2022-10-27 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_companyprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='organizational_interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='organizational interface'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='telephone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
