# Generated by Django 4.1 on 2022-12-18 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_educational_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=10, null=True, verbose_name='Slug Field'),
        ),
        migrations.AddField(
            model_name='language',
            name='user',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='educationalrecord',
            name='grade',
            field=models.FloatField(default=0, verbose_name='Grade'),
        ),
    ]
