# Generated by Django 4.1 on 2022-11-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_companyprofile_organizational_interface_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='name'),
        ),
    ]
