# Generated by Django 4.1 on 2022-11-03 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_companyprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='organizational_interface',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='organizational interface'),
        ),
    ]
