# Generated by Django 4.1 on 2022-12-18 12:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_educationalrecord_user_alter_language_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='month_of_birth',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(12)], verbose_name='month of birth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year_of_birth',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(message='The year is Invalid.', regex='^1[34]\\d{2}$')], verbose_name='year of birth'),
        ),
    ]
