# Generated by Django 4.1 on 2022-11-05 08:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_companyprofile_organizational_interface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='The year is Invalid.', regex='^13\\d{2}')], verbose_name='established year'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='organizational_interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='organizational interface'),
        ),
    ]
