# Generated by Django 4.1 on 2022-08-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_otpdocument_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpdocument',
            name='expire_at',
            field=models.DateTimeField(verbose_name='Expired_at'),
        ),
    ]
