# Generated by Django 4.1 on 2022-11-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_companyprofile_established_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_email_code',
            field=models.CharField(editable=False, max_length=32),
        ),
    ]
