# Generated by Django 4.1 on 2022-12-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_month_of_birth_alter_profile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='educational_record',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_experience',
            field=models.JSONField(default={}),
        ),
        migrations.DeleteModel(
            name='EducationalRecord',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='WorkExperience',
        ),
    ]
