# Generated by Django 4.1 on 2022-11-05 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_active_email_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='organizational_interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='organizational interface'),
        ),
    ]
