# Generated by Django 4.1 on 2022-12-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_language_user_remove_workexperience_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='educational_record',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_experience',
            field=models.JSONField(default=dict),
        ),
    ]
