# Generated by Django 4.1 on 2022-12-19 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import extensions.utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_educational_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='About Me'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='national_code',
            field=models.CharField(max_length=10, validators=[extensions.utils.national_code_validator], verbose_name='National_code'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
