# Generated by Django 4.1 on 2022-08-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_otpdocument_expire_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpdocument',
            name='expire_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Expired_at'),
        ),
    ]
