# Generated by Django 4.1 on 2022-11-06 09:02

from django.db import migrations, models
import extensions.utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_resume_remove_educationalrecord_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[extensions.utils.email_validator], verbose_name='email'),
        ),
    ]
