# Generated by Django 4.1 on 2022-08-17 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_otpdocument_expire_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpdocument',
            name='expire_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Expired_at'),
        ),
    ]
