# Generated by Django 4.1 on 2022-08-17 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_otpdocument_expire_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpdocument',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime.utcnow, verbose_name='Expired_at'),
        ),
    ]
