# Generated by Django 4.1 on 2022-12-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_educational_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='educational_record',
            field=models.JSONField(default={'grade': 0, 'major': '', 'university': ''}),
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.JSONField(default={'language': ''}),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_experience',
            field=models.JSONField(default={'company': '', 'job': ''}),
        ),
    ]
