# Generated by Django 4.1 on 2022-11-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_cv_remove_resume_user_profile_about_me_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='employment_period',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
