# Generated by Django 4.1 on 2022-12-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_profile_educational_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='work_experience',
            field=models.JSONField(default={'company': 'mo', 'job': 'mo'}),
        ),
    ]
