# Generated by Django 4.1 on 2022-11-09 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import extensions.utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_workexperience_employment_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='employment_period',
        ),
        migrations.AddField(
            model_name='educationalrecord',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[extensions.utils.national_code_validator], verbose_name='national_code'),
        ),
        migrations.AddField(
            model_name='profile',
            name='province',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='province'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(default='Iran', max_length=200, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='military_service_status',
            field=models.CharField(blank=True, choices=[('دارای کارت پایان خدمت', 'دارای کارت پایان خدمت'), ('در حال خدمت', 'در حال خدمت'), ('معاف از رزم', 'معاف از رزم'), ('معافیت تحصیلی', 'معافیت تحصیلی'), ('معافیت پزشکی', 'معافیت پزشکی'), ('سایر معافیت ها', 'سایر معافیت ها')], max_length=100, null=True, verbose_name='Military Service Status'),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=10, null=True, verbose_name='Slug Field')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Language')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
    ]
