# Generated by Django 4.1 on 2022-08-17 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_otpdocument_expire_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpdocument',
            name='expire_at',
        ),
        migrations.AddField(
            model_name='otpdocument',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create_at'),
        ),
        migrations.AddField(
            model_name='otpdocument',
            name='retry',
            field=models.IntegerField(default=0, verbose_name='Retry'),
        ),
    ]
