# Generated by Django 4.1 on 2022-12-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_profile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='educational_record',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_experience',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
