# Generated by Django 4.1 on 2022-12-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_profile_educational_record_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='industry',
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='industry',
            field=models.JSONField(blank=True, default=dict, verbose_name='industry'),
        ),
    ]
