# Generated by Django 4.1 on 2022-12-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_companyprofile_industry_delete_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='logo'),
        ),
    ]
