# Generated by Django 4.1 on 2022-08-17 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_otpdocument_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpdocument',
            name='code',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(111111)], verbose_name='Otp Code'),
        ),
    ]
