# Generated by Django 4.1 on 2022-12-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_companyprofile_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=models.FilePathField(blank=True, null=True, verbose_name='logo'),
        ),
    ]
