# Generated by Django 4.1 on 2022-12-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_companyprofile_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_view',
            field=models.ImageField(blank=True, null=True, upload_to='view/', verbose_name='company view'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(upload_to='logo/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cv_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='CV File'),
        ),
    ]
