# Generated by Django 4.1 on 2022-09-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_user_is_active_remove_user_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.CharField(choices=[('normal', 'یوزر عادی'), ('admin', 'ادمین'), ('superuser', 'ابر یوزر')], default='normal', max_length=9, verbose_name='User Level'),
        ),
    ]
