# Generated by Django 4.1 on 2022-12-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_companyprofile_logo_alter_profile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(upload_to='logo/', verbose_name='logo'),
        ),
    ]
