# Generated by Django 4.1 on 2022-12-25 15:07

from django.db import migrations, models
import extensions.utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_companyprofile_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_view',
            field=models.URLField(blank=True, validators=[extensions.utils.url_validator], verbose_name='company view'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=models.URLField(blank=True, validators=[extensions.utils.url_validator], verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cv_file',
            field=models.URLField(blank=True, validators=[extensions.utils.url_validator], verbose_name='CV File'),
        ),
    ]
