# Generated by Django 4.1 on 2022-09-08 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_user_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='شماره ی تلفن نامعتبر است.', regex='^9\\d{2}\\s*?\\d{3}\\s*?\\d{4}$')], verbose_name='phone')),
            ],
            options={
                'verbose_name': 'Blocked Phone',
                'verbose_name_plural': 'Blocked Phones',
            },
        ),
    ]
