# Generated by Django 4.1 on 2022-09-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_otpdocument_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpdocument',
            name='contact',
            field=models.CharField(max_length=12, unique=True, verbose_name='Contact'),
        ),
    ]
