# Generated by Django 4.1 on 2022-09-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_otpdocument_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpdocument',
            name='create_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Create_at'),
        ),
    ]
