# Generated by Django 4.1 on 2022-09-10 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_otpdocument_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpdocument',
            name='contact',
            field=models.CharField(max_length=11, unique=True, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='شماره ی تلفن نامعتبر است.', regex='^9\\d{2}\\s*?\\d{3}\\s*?\\d{4}$')], verbose_name='phone'),
        ),
    ]
