# Generated by Django 4.1 on 2022-09-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_otpdocument_id_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.CharField(choices=[('normal', 'normal'), ('admin', 'admin'), ('super_user', 'super_user')], default='normal', max_length=10, verbose_name='user level'),
        ),
        migrations.AlterField(
            model_name='user',
            name='active_email_code',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
