# Generated by Django 4.1 on 2022-09-20 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_user_is_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtpDocument',
        ),
    ]
