# Generated by Django 4.1 on 2022-09-21 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_personalinformation_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.CharField(blank=True, default='None', max_length=500, null=True, verbose_name='About Me')),
            ],
        ),
        migrations.CreateModel(
            name='EducationalRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(blank=True, max_length=30, null=True, verbose_name='Major')),
                ('university', models.CharField(blank=True, max_length=100, null=True, verbose_name='University')),
                ('grade', models.CharField(blank=True, choices=[('Diploma', 'diploma'), ('Associate', 'associate'), ('MA', 'master'), ('MS', 'master of science'), ('Dr', 'doctorate')], max_length=30, null=True, verbose_name='Grade')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(blank=True, max_length=100, null=True, verbose_name='Job')),
                ('company', models.CharField(blank=True, max_length=150, null=True, verbose_name='Company')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='personal_information',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.personalinformation'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date Of Birth'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=6, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='is_married',
            field=models.BooleanField(default=False, verbose_name='Is Married ?'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='military_service_status',
            field=models.CharField(blank=True, choices=[('end of service', 'the end of service'), ('permanent exemption', 'permanent exemption'), ('education pardon', 'education pardon'), ('doing', 'doing'), ('included', 'included')], max_length=100, null=True, verbose_name='Military Service Status'),
        ),
        migrations.AddField(
            model_name='profile',
            name='about_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.aboutme'),
        ),
        migrations.AddField(
            model_name='profile',
            name='educational_records',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.educationalrecords'),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.workexperience'),
        ),
    ]
