# Generated by Django 4.1 on 2022-09-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_aboutme_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='slug',
            field=models.SlugField(blank=True, max_length=10, null=True, verbose_name='Slug Field'),
        ),
        migrations.AlterField(
            model_name='educationalrecord',
            name='slug',
            field=models.SlugField(blank=True, max_length=10, null=True, verbose_name='Slug Field'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='slug',
            field=models.SlugField(blank=True, max_length=10, null=True, verbose_name='Slug Field'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, max_length=10, null=True, verbose_name='Slug Field'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='slug',
            field=models.SlugField(blank=True, max_length=10, null=True, verbose_name='Slug Field'),
        ),
    ]
