# Generated by Django 4.1 on 2022-09-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_alter_aboutme_slug_alter_educationalrecord_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=10, null=True, verbose_name='Slug Field'),
        ),
        migrations.AlterField(
            model_name='educationalrecord',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=10, null=True, verbose_name='Slug Field'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'F'), ('Male', 'M')], max_length=6, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=10, null=True, verbose_name='Slug Field'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=10, null=True, verbose_name='Slug Field'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=10, null=True, verbose_name='Slug Field'),
        ),
    ]
