# Generated by Django 4.1 on 2022-10-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_aboutme_slug_alter_educationalrecord_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalrecord',
            name='grade',
            field=models.CharField(blank=True, choices=[('diploma', 'Diploma'), ('associate', 'Associate'), ('master', 'MA'), ('master of science', 'MS'), ('doctorate', 'Dr')], max_length=30, null=True, verbose_name='Grade'),
        ),
    ]
