# Generated by Django 4.1 on 2022-10-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_alter_educationalrecord_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('english_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='english name')),
                ('website_addr', models.CharField(blank=True, max_length=120, null=True, verbose_name='website address')),
                ('telephone', models.CharField(max_length=10)),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='city')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='logo')),
                ('company_description', models.TextField(blank=True, max_length=400, null=True, verbose_name='company description')),
                ('company_view', models.ImageField(blank=True, null=True, upload_to='', verbose_name='company view')),
                ('established_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='established year')),
                ('type_of_ownership', models.CharField(blank=True, choices=[('Private', 'Private'), ('Government', 'Government'), ('Other', 'Non-profit/Charity')], max_length=10, null=True, verbose_name='type of ownership')),
                ('industry', models.ManyToManyField(blank=True, null=True, to='accounts.companyprofile', verbose_name='industry')),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Companies Profile',
            },
        ),
    ]
