# Generated by Django 4.1 on 2022-10-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_companyprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='industry',
            field=models.ManyToManyField(to='accounts.companyprofile', verbose_name='industry'),
        ),
    ]
