# Generated by Django 4.1 on 2022-10-05 19:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_industry_alter_companyprofile_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='type of company'),
        ),
        migrations.CreateModel(
            name='OrganizationalInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75, verbose_name='first name')),
                ('last_name', models.CharField(max_length=75, verbose_name='last name')),
                ('organization_level', models.CharField(max_length=75, verbose_name='organization level')),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='The phone number is Invalid.', regex='^9\\d{2}\\s*?\\d{3}\\s*?\\d{4}$')], verbose_name='phone')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.companyprofile', verbose_name='company')),
            ],
            options={
                'verbose_name': 'Organizational Interface',
                'verbose_name_plural': 'Organizational Interfaces',
            },
        ),
    ]
