# Generated by Django 4.1 on 2022-10-08 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_alter_companyprofile_email_alter_companyprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationalinterface',
            name='company',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='organizational_interface',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organizationalinterface', verbose_name='organizational interface'),
        ),
    ]
