# Generated by Django 4.1 on 2022-10-09 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_remove_organizationalinterface_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='create at'),
            preserve_default=False,
        ),
    ]
