# Generated by Django 4.1 on 2022-10-09 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_companyprofile_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(4), django.core.validators.MinLengthValidator(4)], verbose_name='established year'),
        ),
    ]
