# Generated by Django 4.1 on 2022-10-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_alter_companyprofile_established_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='established year'),
        ),
    ]
