# Generated by Django 4.1 on 2022-10-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_alter_companyprofile_established_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='industry',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.industry', verbose_name='industry'),
        ),
    ]
