# Generated by Django 4.1 on 2022-10-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_alter_companyprofile_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalinterface',
            name='first_name',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='organizationalinterface',
            name='last_name',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='organizationalinterface',
            name='organization_level',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='organization level'),
        ),
    ]
