# Generated by Django 4.1 on 2022-10-11 18:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_alter_organizationalinterface_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalinterface',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='The phone number is Invalid.', regex='^9\\d{2}\\s*?\\d{3}\\s*?\\d{4}$')], verbose_name='phone'),
        ),
    ]
