# Generated by Django 4.1 on 2022-10-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_alter_organizationalinterface_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalinterface',
            name='access_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='organizationalinterface',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
