# Generated by Django 4.1 on 2022-10-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_organizationalinterface_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationalinterface',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='organizationalinterface',
            name='refresh_token',
        ),
        migrations.AddField(
            model_name='organizationalinterface',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='password'),
        ),
    ]
