# Generated by Django 4.1 on 2022-10-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_remove_organizationalinterface_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalinterface',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='slug'),
        ),
    ]
