# Generated by Django 4.1 on 2022-10-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_organizationalinterface_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationalinterface',
            name='password_confirm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='password confirm'),
        ),
    ]
