# Generated by Django 4.1 on 2022-10-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_organizationalinterface_password_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationalinterface',
            name='password_confirm',
        ),
    ]
