# Generated by Django 4.1 on 2022-10-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_remove_organizationalinterface_password_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='industry',
            field=models.ManyToManyField(to='accounts.industry', verbose_name='industry'),
        ),
    ]
