# Generated by Django 4.1 on 2022-10-18 20:21

from django.db import migrations, models
import extensions.utils


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_alter_companyprofile_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationalinterface',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[extensions.utils.phone_validation], verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[extensions.utils.phone_validation], verbose_name='phone'),
        ),
    ]
